services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: devops-test-app
        restart: unless-stopped
        volumes:
            - storage-data:/var/www/storage
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env.docker
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: devops-test-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/var/www/public:ro
        depends_on:
            - app
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: devops-test-frontend
        restart: unless-stopped
        ports:
            - "3000:80"
        depends_on:
            - nginx
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: devops-test-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: devops_test
            MYSQL_ROOT_PASSWORD: "12345678"
            MYSQL_USER: devops_test
            MYSQL_PASSWORD: "12345678"
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app-network

volumes:
    db-data:
    storage-data:

networks:
    app-network:
        driver: bridge
